# Generated by Django 3.1.7 on 2022-07-19 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plano_de_acao', '0029_plano_de_acao_tipo_fia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo_fia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_caixa_escolar', models.CharField(blank=True, max_length=50)),
                ('ano_exercicio', models.IntegerField(blank=True, default=0)),
                ('discriminacao', models.CharField(blank=True, max_length=900)),
                ('quantidade', models.IntegerField(blank=True, default=0)),
                ('preco_unitario_item', models.IntegerField(blank=True, default=0)),
                ('valor_total_anterior', models.IntegerField(blank=True, default=0)),
                ('valor_total_atual', models.IntegerField(blank=True, default=0)),
                ('valor_total_fia', models.IntegerField(blank=True, default=0)),
                ('justificativa', models.CharField(blank=True, max_length=900)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano_de_acao.plano_de_acao')),
            ],
        ),
        migrations.CreateModel(
            name='Extra_fia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discriminacao', models.CharField(blank=True, max_length=900)),
                ('quantidade', models.IntegerField(blank=True, default=0)),
                ('preco_unitario_item', models.IntegerField(blank=True, default=0)),
                ('valor_total_atual', models.IntegerField(blank=True, default=0)),
                ('justificativa', models.CharField(blank=True, max_length=900)),
                ('fia_matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fia.modelo_fia')),
            ],
        ),
    ]
