# Generated by Django 3.1.7 on 2022-07-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_fia',
            name='valor_numerico',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
