# Generated by Django 3.1.7 on 2022-07-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0002_extra_fia_valor_numerico'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_fia',
            name='valor_numerico',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
