# Generated by Django 3.1.7 on 2022-07-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0003_modelo_fia_valor_numerico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_fia',
            name='preco_unitario_item',
            field=models.DecimalField(decimal_places=2, max_digits=14, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extra_fia',
            name='valor_total_atual',
            field=models.DecimalField(decimal_places=2, max_digits=14, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelo_fia',
            name='ano_exercicio',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='modelo_fia',
            name='preco_unitario_item',
            field=models.DecimalField(decimal_places=2, max_digits=14, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelo_fia',
            name='valor_total_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=14, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelo_fia',
            name='valor_total_atual',
            field=models.DecimalField(decimal_places=2, max_digits=14, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelo_fia',
            name='valor_total_fia',
            field=models.DecimalField(decimal_places=2, max_digits=14, max_length=50, null=True),
        ),
    ]
