# Generated by Django 3.1.7 on 2022-07-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0004_auto_20220719_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_fia',
            name='ano_exercicio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
