# Generated by Django 3.1.7 on 2022-07-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0005_auto_20220719_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_fia',
            name='valor_total_item',
            field=models.DecimalField(decimal_places=2, max_digits=14, max_length=50, null=True),
        ),
    ]
