# Generated by Django 3.1.7 on 2022-07-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0006_modelo_fia_valor_total_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_fia',
            name='valor_total_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, max_length=50, null=True),
        ),
    ]
