# Generated by Django 3.1.7 on 2022-07-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0007_auto_20220720_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_fia',
            name='nome_caixa_escolar',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
