# Generated by Django 3.1.7 on 2022-07-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0008_auto_20220720_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra_fia',
            old_name='valor_total_atual',
            new_name='valor_total_item',
        ),
    ]
