# Generated by Django 3.1.7 on 2022-07-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0009_auto_20220720_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_fia',
            name='possui_sugestao_correcao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelo_fia',
            name='possui_sugestao_correcao',
            field=models.BooleanField(default=False),
        ),
    ]
