# Generated by Django 3.1.7 on 2022-08-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0010_auto_20220728_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_fia',
            name='assinatura_tecnico',
            field=models.ImageField(blank=True, null=True, upload_to='SetupPrincipal/img/signs', verbose_name='Assinatura'),
        ),
    ]
