# Generated by Django 3.1.7 on 2022-08-12 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0031_plano_de_acao_pre_analise_fia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fia', '0011_modelo_fia_assinatura_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_fia',
            name='membro_colegiado_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membro1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelo_fia',
            name='membro_colegiado_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membro2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelo_fia',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano', to='plano_de_acao.plano_de_acao'),
        ),
    ]
