# Generated by Django 3.1.7 on 2022-08-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0014_auto_20220816_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_fia',
            name='quebra_de_linha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelo_fia',
            name='quebra_de_linha',
            field=models.IntegerField(default=0),
        ),
    ]
