# Generated by Django 3.1.7 on 2022-10-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0015_auto_20220829_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_fia',
            name='preco_unitario_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, max_length=50, null=True),
        ),
    ]
