# Generated by Django 3.1.7 on 2021-04-08 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano_de_acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.CharField(max_length=50)),
                ('descricao_plano', models.CharField(max_length=300)),
                ('prazo_execucao_inicial', models.DateField()),
                ('prazo_execucao_final', models.DateField()),
                ('resultados_esperados', models.CharField(max_length=300)),
                ('date_plano', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
    ]
