# Generated by Django 3.1.7 on 2021-04-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0004_auto_20210408_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano_de_acao',
            name='descricao_plano',
        ),
        migrations.RemoveField(
            model_name='plano_de_acao',
            name='prazo_execucao_final',
        ),
        migrations.RemoveField(
            model_name='plano_de_acao',
            name='prazo_execucao_inicial',
        ),
        migrations.RemoveField(
            model_name='plano_de_acao',
            name='resultados_esperados',
        ),
    ]
