# Generated by Django 3.1.7 on 2021-04-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0005_auto_20210408_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='ordens',
            field=models.IntegerField(default=0),
        ),
    ]
