# Generated by Django 3.1.7 on 2021-04-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0006_plano_de_acao_ordens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano_de_acao',
            old_name='date_plano',
            new_name='data_de_criação',
        ),
        migrations.RemoveField(
            model_name='plano_de_acao',
            name='ordens',
        ),
    ]
