# Generated by Django 3.1.7 on 2021-04-20 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plano_de_acao', '0008_plano_de_acao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano_de_acao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
