# Generated by Django 3.1.7 on 2021-04-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0009_auto_20210420_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='situacao',
            field=models.CharField(default='Em desenvolvimento', max_length=50),
        ),
    ]
