# Generated by Django 3.1.7 on 2021-07-14 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0010_plano_de_acao_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_de_eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50)),
                ('momento_do_ocorrido', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano_de_acao.plano_de_acao')),
            ],
        ),
    ]
