# Generated by Django 3.1.7 on 2021-07-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0011_log_de_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='assinaturas',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
