# Generated by Django 3.1.7 on 2021-07-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0012_plano_de_acao_assinaturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='user_autorizou',
            field=models.BooleanField(default=False),
        ),
    ]
