# Generated by Django 3.1.7 on 2022-02-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0013_plano_de_acao_user_autorizou'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='correcao_a_fazer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plano_de_acao',
            name='pre_analise',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
