# Generated by Django 3.1.7 on 2022-03-09 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0014_auto_20220224_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano_de_acao',
            name='correcao_a_fazer',
        ),
        migrations.AddField(
            model_name='plano_de_acao',
            name='correcoes_a_fazer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Correcoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_associado', models.CharField(max_length=50)),
                ('ordem_associada', models.IntegerField(blank=True)),
                ('codigo_associado', models.CharField(max_length=5)),
                ('sugestao', models.TextField(max_length=700)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano_de_acao.plano_de_acao')),
            ],
        ),
    ]
