# Generated by Django 3.1.7 on 2022-03-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0015_auto_20220309_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correcoes',
            name='sugestao',
            field=models.TextField(max_length=1400),
        ),
    ]
