# Generated by Django 3.1.7 on 2022-03-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0017_auto_20220309_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correcoes',
            name='plano',
        ),
        migrations.AddField(
            model_name='correcoes',
            name='plano_nome',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
