# Generated by Django 3.1.7 on 2022-03-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0018_auto_20220309_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='correcoes',
            name='plano_associado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='plano_de_acao.plano_de_acao'),
            preserve_default=False,
        ),
    ]
