# Generated by Django 3.1.7 on 2022-03-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0020_remove_plano_de_acao_pre_analise'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='pre_analise_acao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plano_de_acao',
            name='pre_analise_despesa',
            field=models.BooleanField(default=False),
        ),
    ]
