# Generated by Django 3.1.7 on 2022-03-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0021_auto_20220312_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
    ]
