# Generated by Django 3.1.7 on 2022-05-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0022_plano_de_acao_devolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='assinaturas_sec',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
