# Generated by Django 3.1.7 on 2022-05-13 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plano_de_acao', '0024_plano_de_acao_pre_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='corretor_plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corretor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plano_de_acao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Criador', to=settings.AUTH_USER_MODEL),
        ),
    ]
