# Generated by Django 3.1.7 on 2022-07-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0025_auto_20220513_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='alterabilidade',
            field=models.BooleanField(default=True),
        ),
    ]
