# Generated by Django 3.1.7 on 2022-07-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0026_plano_de_acao_alterabilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano_de_acao',
            name='alterabilidade',
        ),
    ]
