# Generated by Django 3.1.7 on 2022-07-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0027_remove_plano_de_acao_alterabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='alterabilidade',
            field=models.CharField(default='Escola', max_length=50),
        ),
    ]
