# Generated by Django 3.1.7 on 2022-07-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0028_plano_de_acao_alterabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='tipo_fia',
            field=models.BooleanField(default=False),
        ),
    ]
