# Generated by Django 3.1.7 on 2022-07-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0029_plano_de_acao_tipo_fia'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='forca_criacao_modelo_fia',
            field=models.BooleanField(default=False),
        ),
    ]
