# Generated by Django 3.1.7 on 2022-07-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0030_plano_de_acao_forca_criacao_modelo_fia'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='pre_analise_fia',
            field=models.BooleanField(default=False),
        ),
    ]
