# Generated by Django 3.1.7 on 2022-08-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0031_plano_de_acao_pre_analise_fia'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='data_assinaturas_escola',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano_de_acao',
            name='data_assinaturas_suprof',
            field=models.DateField(blank=True, null=True),
        ),
    ]
