# Generated by Django 3.1.7 on 2022-08-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0032_auto_20220825_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='assinatura_coordenador',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='plano_de_acao',
            name='assinatura_corretor',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='plano_de_acao',
            name='assinatura_diretor',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
