# Generated by Django 3.1.7 on 2022-08-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0033_auto_20220831_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano_de_acao',
            name='assinatura_coordenador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plano_de_acao',
            name='assinatura_corretor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plano_de_acao',
            name='assinatura_diretor',
            field=models.BooleanField(default=False),
        ),
    ]
