# Generated by Django 3.1.7 on 2022-09-16 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0034_auto_20220831_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano_de_acao',
            name='usuario',
        ),
    ]
