# Generated by Django 3.1.7 on 2022-09-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0037_auto_20220915_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_de_acao',
            name='comando_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plano_de_acao',
            name='comando_todas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plano_de_acao',
            name='todas_inseridas',
            field=models.BooleanField(default=False),
        ),
    ]
