# Generated by Django 3.1.7 on 2022-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0038_auto_20220929_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano_de_acao',
            name='comando_todas',
            field=models.BooleanField(default=True),
        ),
    ]
