# Generated by Django 3.1.7 on 2021-04-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identificacao_numerica', models.IntegerField(max_length=50)),
                ('descricao_da_ordem', models.TextField(max_length=500)),
                ('prazo_execucao_inicial', models.DateField()),
                ('prazo_execucao_final', models.DateField()),
                ('resultados_esperados', models.TextField(max_length=500)),
            ],
        ),
    ]
