# Generated by Django 3.1.7 on 2021-04-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordens',
            name='Identificacao_numerica',
            field=models.IntegerField(),
        ),
    ]
