# Generated by Django 3.1.7 on 2021-04-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0002_auto_20210408_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordens',
        ),
    ]
