# Generated by Django 3.1.7 on 2021-04-28 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0010_plano_de_acao_situacao'),
        ('Ordens', '0004_ordens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordens',
            old_name='descricao_da_ordem',
            new_name='descricao_do_problema',
        ),
        migrations.AddField(
            model_name='ordens',
            name='plano',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='plano_de_acao.plano_de_acao'),
            preserve_default=False,
        ),
    ]
