# Generated by Django 3.1.7 on 2021-05-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0006_auto_20210428_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleOrdens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todas_inseridas', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='ordens',
            name='inserida',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
