# Generated by Django 3.1.7 on 2021-05-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0007_auto_20210514_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleordens',
            name='comando_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controleordens',
            name='comando_todas',
            field=models.BooleanField(default=False),
        ),
    ]
