# Generated by Django 3.1.7 on 2021-05-14 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0008_auto_20210514_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordens',
            name='data_de_criação',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
