# Generated by Django 3.1.7 on 2021-05-14 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0009_ordens_data_de_criação'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordens',
            name='data_de_criação',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
