# Generated by Django 3.1.7 on 2021-05-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0010_auto_20210514_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordens',
            name='inserida',
            field=models.BooleanField(default=False),
        ),
    ]
