# Generated by Django 3.1.7 on 2021-05-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0011_auto_20210514_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleCodigosDaOrdem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_codigos_inseridos', models.IntegerField(default=0)),
            ],
        ),
    ]
