# Generated by Django 3.1.7 on 2021-05-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0012_controlecodigosdaordem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControleCodigosDaOrdem',
        ),
        migrations.AddField(
            model_name='ordens',
            name='codigos_inseridos',
            field=models.IntegerField(default=0),
        ),
    ]
