# Generated by Django 3.1.7 on 2021-05-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0013_auto_20210515_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleordens',
            name='var_template',
            field=models.IntegerField(default=0),
        ),
    ]
