# Generated by Django 3.1.7 on 2021-05-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0014_controleordens_var_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controleordens',
            name='var_template',
        ),
        migrations.AddField(
            model_name='ordens',
            name='ordem_rowspan',
            field=models.IntegerField(default=1),
        ),
    ]
