# Generated by Django 3.1.7 on 2021-05-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0015_auto_20210516_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordens',
            name='ordem_rowspan',
            field=models.IntegerField(default=0),
        ),
    ]
