# Generated by Django 3.1.7 on 2022-04-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0018_ordens_possui_sugestao_correcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordens',
            name='prazo_execucao_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordens',
            name='prazo_execucao_inicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
