# Generated by Django 3.1.7 on 2022-07-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0019_auto_20220428_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordens',
            name='quebra_de_linha',
            field=models.IntegerField(default=0),
        ),
    ]
