# Generated by Django 3.1.7 on 2022-10-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0020_ordens_quebra_de_linha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordens',
            name='identificacao_numerica',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
