# Generated by Django 3.1.7 on 2021-05-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloCodigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=10)),
                ('especificacao', models.CharField(max_length=500)),
                ('justificativa', models.CharField(max_length=500)),
                ('embalagem', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
