# Generated by Django 3.1.7 on 2021-05-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0003_auto_20210505_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelocodigos',
            name='preco_unitario_currency',
        ),
        migrations.AddField(
            model_name='modelocodigos',
            name='preco_total_capital',
            field=models.DecimalField(decimal_places=2, max_digits=14, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modelocodigos',
            name='preco_total_custeio',
            field=models.DecimalField(decimal_places=2, max_digits=14, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('caixa', 'caixa'), ('unidade', 'unidade')], max_length=10),
        ),
        migrations.AlterField(
            model_name='modelocodigos',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=14, max_length=50, null=True),
        ),
    ]
