# Generated by Django 3.1.7 on 2021-05-05 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0006_auto_20210428_0053'),
        ('codigos', '0005_auto_20210505_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('caixa', 'caixa'), ('unidade', 'unidade')], max_length=10),
        ),
        migrations.AlterField(
            model_name='modelocodigos',
            name='ordem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ordens.ordens'),
        ),
    ]
