# Generated by Django 3.1.7 on 2021-05-12 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ordens', '0006_auto_20210428_0053'),
        ('codigos', '0006_auto_20210505_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ordens.ordens'),
        ),
    ]
