# Generated by Django 3.1.7 on 2021-05-14 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0009_auto_20210514_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelocodigos',
            name='data_de_criação',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('unidade', 'unidade'), ('caixa', 'caixa')], max_length=10),
        ),
    ]
