# Generated by Django 3.1.7 on 2021-05-14 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0010_auto_20210514_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='data_de_criação',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
