# Generated by Django 3.1.7 on 2021-05-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0012_auto_20210514_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelocodigos',
            name='inserido',
            field=models.BooleanField(default=False),
        ),
    ]
