# Generated by Django 3.1.7 on 2021-05-18 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0015_auto_20210516_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='data_de_criação',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('unidade', 'unidade'), ('caixa', 'caixa')], max_length=10),
        ),
    ]
