# Generated by Django 3.1.7 on 2021-06-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0018_auto_20210521_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelocodigos',
            name='preco_total_capital',
        ),
        migrations.RemoveField(
            model_name='modelocodigos',
            name='preco_total_custeio',
        ),
        migrations.AddField(
            model_name='modelocodigos',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, max_digits=14, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modelocodigos',
            name='tipo_produto',
            field=models.CharField(choices=[('capital', 'capital'), ('custeio', 'custeio')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('unidade', 'unidade'), ('caixa', 'caixa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='modelocodigos',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
