# Generated by Django 3.1.7 on 2021-07-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0026_auto_20210616_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('unidade', 'unidade'), ('caixa', 'caixa')], max_length=10),
        ),
    ]
