# Generated by Django 3.1.7 on 2021-07-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0036_auto_20210716_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='tipo_produto',
            field=models.CharField(choices=[('Custeio', 'Custeio'), ('Capital', 'Capital')], max_length=10),
        ),
    ]
