# Generated by Django 3.1.7 on 2021-07-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0045_auto_20210716_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='tipo_produto',
            field=models.CharField(choices=[('Capital', 'Capital'), ('Custeio', 'Custeio')], max_length=10),
        ),
    ]
