# Generated by Django 3.1.7 on 2021-07-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0052_auto_20210717_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('caixa', 'caixa'), ('unidade', 'unidade')], max_length=10),
        ),
    ]
