# Generated by Django 3.1.7 on 2022-02-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0054_auto_20210730_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('caixa', 'caixa'), ('unidade', 'unidade')], max_length=10),
        ),
    ]
