# Generated by Django 3.1.7 on 2022-03-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0062_auto_20220312_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelocodigos',
            name='possui_sugestao_correcao',
            field=models.BooleanField(default=False),
        ),
    ]
