# Generated by Django 3.1.7 on 2022-03-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0064_auto_20220314_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='identificacao',
            field=models.CharField(max_length=2),
        ),
    ]
