# Generated by Django 3.1.7 on 2022-05-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0067_auto_20220502_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('caixa', 'caixa'), ('unidade', 'unidade')], max_length=10),
        ),
    ]
