# Generated by Django 3.1.7 on 2022-07-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0073_auto_20220627_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('unidade', 'unidade'), ('caixa', 'caixa')], max_length=10),
        ),
    ]
