# Generated by Django 3.1.7 on 2022-07-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0082_auto_20220719_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='tipo_produto',
            field=models.CharField(choices=[('Custeio', 'Custeio'), ('Capital', 'Capital')], max_length=10),
        ),
    ]
