# Generated by Django 3.1.7 on 2022-07-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0085_auto_20220720_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('unidade', 'unidade'), ('caixa', 'caixa')], max_length=10),
        ),
    ]
