# Generated by Django 3.1.7 on 2022-07-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0086_auto_20220720_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('caixa', 'caixa'), ('unidade', 'unidade')], max_length=10),
        ),
    ]
