# Generated by Django 3.1.7 on 2022-08-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0092_auto_20220812_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('unidade', 'unidade'), ('caixa', 'caixa')], max_length=10),
        ),
    ]
