# Generated by Django 3.1.7 on 2022-08-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0094_auto_20220825_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelocodigos',
            name='quebra_de_linha',
            field=models.IntegerField(default=0),
        ),
    ]
