# Generated by Django 3.1.7 on 2022-09-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0114_auto_20220916_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='tipo_produto',
            field=models.CharField(choices=[('Capital', 'Capital'), ('Custeio', 'Custeio')], max_length=10),
        ),
    ]
