# Generated by Django 3.1.7 on 2022-09-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0115_auto_20220916_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('caixa', 'caixa'), ('unidade', 'unidade')], max_length=10),
        ),
    ]
