# Generated by Django 3.1.7 on 2022-10-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0120_auto_20220930_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('caixa', 'caixa'), ('unidade', 'unidade')], max_length=10),
        ),
        migrations.AlterField(
            model_name='modelocodigos',
            name='quebra_de_linha',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='modelocodigos',
            name='tipo_produto',
            field=models.CharField(choices=[('Custeio', 'Custeio'), ('Capital', 'Capital')], max_length=10),
        ),
    ]
