# Generated by Django 3.1.7 on 2022-11-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0125_auto_20221025_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='tipo_produto',
            field=models.CharField(choices=[('Custeio', 'Custeio'), ('Capital', 'Capital')], max_length=10),
        ),
    ]
