# Generated by Django 4.1.4 on 2022-12-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0130_alter_modelocodigos_tipo_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocodigos',
            name='embalagem',
            field=models.CharField(choices=[('caixa', 'caixa'), ('unidade', 'unidade')], max_length=10),
        ),
    ]
