# Generated by Django 3.1.7 on 2021-04-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_classificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='municipio',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
