# Generated by Django 3.1.7 on 2021-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_controleturmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmas',
            name='inserida',
            field=models.BooleanField(default=False),
        ),
    ]
