# Generated by Django 3.1.7 on 2021-06-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_turmas_inserida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControleTurmas',
        ),
        migrations.RemoveField(
            model_name='turmas',
            name='inserida',
        ),
    ]
