# Generated by Django 3.1.7 on 2021-06-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0010_plano_de_acao_situacao'),
        ('usuarios', '0010_turmas_plano_associado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmas',
            name='plano_associado',
        ),
        migrations.CreateModel(
            name='Turmas_plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_alunos', models.IntegerField()),
                ('plano_associado', models.ManyToManyField(to='plano_de_acao.Plano_de_acao')),
            ],
        ),
    ]
