# Generated by Django 3.1.7 on 2021-07-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20210616_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='quant_func',
            field=models.CharField(default='', max_length=5),
        ),
    ]
