# Generated by Django 3.1.7 on 2021-07-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_classificacao_quant_func'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='quant_funcionarios',
            field=models.IntegerField(default=0),
        ),
    ]
