# Generated by Django 3.1.7 on 2021-07-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_classificacao_quant_funcionarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificacao',
            name='quant_func',
        ),
    ]
