# Generated by Django 3.1.7 on 2021-07-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0012_plano_de_acao_assinaturas'),
        ('usuarios', '0014_remove_classificacao_quant_func'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='plano_associado',
            field=models.ManyToManyField(to='plano_de_acao.Plano_de_acao'),
        ),
    ]
