# Generated by Django 3.1.7 on 2022-04-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_classificacao_plano_associado'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='assina_plano',
            field=models.BooleanField(default=False),
        ),
    ]
