# Generated by Django 3.1.7 on 2022-06-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_classificacao_assina_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='municipio',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
