# Generated by Django 3.1.7 on 2022-06-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_auto_20220617_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='matriz',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
