# Generated by Django 3.1.7 on 2022-07-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_classificacao_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='codigo_escola',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='classificacao',
            name='nte',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
