# Generated by Django 3.1.7 on 2022-07-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_de_acao', '0029_plano_de_acao_tipo_fia'),
        ('usuarios', '0021_auto_20220718_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmas',
            name='plano_associado',
            field=models.ManyToManyField(to='plano_de_acao.Plano_de_acao'),
        ),
        migrations.DeleteModel(
            name='Turmas_plano',
        ),
    ]
