# Generated by Django 3.1.7 on 2022-08-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_classificacao_usuario_diretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='usuario_coordenador',
            field=models.BooleanField(default=False),
        ),
    ]
