# Generated by Django 3.1.7 on 2022-09-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_classificacao_email_ativado'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='primeira_senha',
            field=models.BooleanField(default=True),
        ),
    ]
