# Generated by Django 3.1.7 on 2022-09-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_classificacao_primeira_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='diretor_escolar',
            field=models.BooleanField(default=False),
        ),
    ]
