# Generated by Django 3.1.7 on 2022-09-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_classificacao_diretor_escolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='possui_diretor',
            field=models.BooleanField(default=False),
        ),
    ]
