# Generated by Django 3.1.7 on 2022-09-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_classificacao_possui_diretor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificacao',
            name='nte',
        ),
    ]
