# Generated by Django 3.1.7 on 2022-09-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0034_remove_classificacao_nte'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='nte',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
