# Generated by Django 3.1.7 on 2022-09-16 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_classificacao_nte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificacao',
            name='codigo_escola',
        ),
        migrations.RemoveField(
            model_name='classificacao',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='classificacao',
            name='nte',
        ),
        migrations.RemoveField(
            model_name='classificacao',
            name='possui_diretor',
        ),
        migrations.RemoveField(
            model_name='classificacao',
            name='quant_funcionarios',
        ),
    ]
