# Generated by Django 3.1.7 on 2022-09-16 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Escolas', '0005_escola_objeto_suprot'),
        ('usuarios', '0038_auto_20220916_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmas',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Escolas.escola'),
        ),
    ]
