# Generated by Django 3.1.7 on 2022-09-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Escolas', '0009_escola_diretor'),
        ('usuarios', '0039_turmas_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Escolas.escola'),
        ),
    ]
