# Generated by Django 3.1.7 on 2022-10-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0040_classificacao_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='marcado_para_exclusao',
            field=models.BooleanField(default=False),
        ),
    ]
