# Generated by Django 3.1.7 on 2022-10-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0041_classificacao_marcado_para_exclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='remocao_solicitante',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
