# Generated by Django 3.1.7 on 2022-10-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0042_classificacao_remocao_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='login_original',
            field=models.BooleanField(default=True),
        ),
    ]
