# Generated by Django 3.1.7 on 2022-09-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('municipio', models.CharField(blank=True, max_length=50)),
                ('codigo_escola', models.IntegerField(blank=True, default=0)),
                ('nte', models.IntegerField(blank=True, null=True)),
                ('quant_funcionarios', models.IntegerField(default=0)),
                ('possui_diretor', models.BooleanField(default=False)),
            ],
        ),
    ]
