# Generated by Django 3.1.7 on 2022-09-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escolas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
