# Generated by Django 3.1.7 on 2022-09-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Escolas', '0005_escola_objeto_suprot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='diretor',
        ),
    ]
