# Generated by Django 3.1.7 on 2022-09-16 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Escolas', '0006_remove_escola_diretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='diretor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
